'use strict';
const CONFIG=window.NYJ20_CONFIG||{}; const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const STORAGE={URL:'nyj20_api_v1',KEY:'nyj20_key_v1',STATION:'nyj20_station_v1'};
let session={url:localStorage.getItem(STORAGE.URL)||String(CONFIG.appsScriptUrl||''),key:localStorage.getItem(STORAGE.KEY)||'',station:localStorage.getItem(STORAGE.STATION)||'관리자 웹'}; let state={settings:{},participants:[]};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(toast.x);toast.x=setTimeout(()=>t.classList.add('hidden'),3500)}
function jsonp(action,payload={}){return new Promise((resolve,reject)=>{const cb='__adm_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');const timer=setTimeout(()=>done(new Error('서버 응답 시간 초과')),30000);function done(e,v){clearTimeout(timer);delete window[cb];s.remove();e?reject(e):resolve(v)}window[cb]=r=>r?.ok?done(null,r.data):done(new Error(r?.error||'처리 실패'));const u=new URL(session.url);u.searchParams.set('action',action);u.searchParams.set('callback',cb);u.searchParams.set('key',session.key);u.searchParams.set('station',session.station);u.searchParams.set('payload',JSON.stringify(payload));s.onerror=()=>done(new Error('서버 연결 실패'));s.src=u;document.head.appendChild(s);});}
function seatText(p){const s=p.seats||[];if(!s.length)return '미정';if(s.length===1)return s[0];const a=s[0],b=s.at(-1);return a.split('-')[0]===b.split('-')[0]?`${a}~${b}`:s.join(', ')}
function totalPeople(){return state.participants.reduce((n,p)=>n+Number(p.participantCount||1),0)}
function render(){const cap=Number(state.settings.registrationCapacity||500),people=totalPeople(),arr=state.participants.filter(p=>p.arrived).reduce((n,p)=>n+Number(p.participantCount||1),0);$('#statPeople').textContent=people;$('#statApps').textContent=state.participants.length;$('#statArrived').textContent=arr;$('#statRemaining').textContent=Math.max(0,cap-people);$('#headerEventName').textContent=state.settings.eventName||'20주년 행사 관리자';$('#lastSyncLabel').textContent=`마지막 동기화 ${new Date().toLocaleTimeString('ko-KR')}`;renderParticipants();renderSeats();renderSettings();}
function renderParticipants(){const q=$('#participantSearch').value.trim().toLowerCase(),f=$('#participantStatusFilter').value;let list=state.participants.filter(p=>!q||[p.name,p.phone,p.organization,p.group,seatText(p),p.number].some(v=>String(v||'').toLowerCase().includes(q)));if(f==='arrived')list=list.filter(p=>p.arrived);if(f==='pending')list=list.filter(p=>!p.arrived);if(f==='unseated')list=list.filter(p=>!(p.seats||[]).length);$('#participantCountLabel').textContent=`${list.length}건`;$('#participantTableBody').innerHTML=list.map(p=>`<tr><td>${String(p.number).padStart(4,'0')}</td><td><strong>${esc(p.name)}</strong><br><small>${esc(p.phone)}</small></td><td>${esc(p.organization||'-')}</td><td>${p.participantCount}명</td><td>${esc(seatText(p))}</td><td><span class="group-chip">${p.arrived?'도착 완료':'미도착'}</span></td><td><button class="button secondary" data-edit="${esc(p.id)}">수정</button> ${p.arrived?`<button class="button secondary" data-undo="${esc(p.id)}">도착취소</button>`:`<button class="button primary" data-checkin="${esc(p.id)}">도착</button>`}</td></tr>`).join('')||'<tr><td colspan="7">표시할 신청자가 없습니다.</td></tr>';}
function rows(){return String(state.settings.seatRows||'A,B,C,D,E,F,G,H,I,J').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean)}
function renderSeats(){const per=Number(state.settings.seatsPerRow||50),owner=new Map();state.participants.forEach(p=>(p.seats||[]).forEach(s=>owner.set(s,p)));$('#seatMap').innerHTML=rows().map(r=>{const reserved=rows().indexOf(r)<rows().indexOf(String(state.settings.autoSeatStartRow||'C').toUpperCase());const seats=Array.from({length:per},(_,i)=>{const id=`${r}-${String(i+1).padStart(2,'0')}`,p=owner.get(id);return p?`<button class="seat ${p.arrived?'arrived':'pending'}" data-seat-edit="${esc(p.id)}"><strong>${id}</strong><small>${esc(p.name)} · ${p.participantCount}명</small></button>`:`<div class="seat empty ${reserved?'reserved':''}"><strong>${id}</strong><small>${reserved?'관리자':'빈 좌석'}</small></div>`}).join('');return `<section class="seat-row-panel"><h3>${r} 구역 <span class="small-text">${reserved?'관리자 배정 구역':'자동 배정 구역'}</span></h3><div class="seat-row">${seats}</div></section>`}).join('');}
function renderSettings(){const s=state.settings;for(const id of ['eventName','eventDate','eventVenue','eventOrganizer','seatRows','seatsPerRow','autoSeatStartRow','registrationCapacity','publicSubtitle','publicGreeting'])if($('#'+id))$('#'+id).value=s[id]??$('#'+id).value;$('#registrationOpen').value=String(s.registrationOpen!==false);$('#autoAssignSeat').value=String(s.autoAssignSeat!==false);}
async function refresh(){const d=await jsonp('bootstrap');state=d;$('#storageBadge').textContent='서버 연결';$('#storageBadge').className='badge success';render();}
function showConnection(){ $('#appsScriptUrlInput').value=session.url||'';$('#adminKeyInput').value=session.key||'';$('#stationNameInput').value=session.station||'관리자 웹';$('#connectionOverlay').classList.remove('hidden');}
$('#connectionForm').addEventListener('submit',async e=>{e.preventDefault();session={url:$('#appsScriptUrlInput').value.trim(),key:$('#adminKeyInput').value.trim(),station:$('#stationNameInput').value.trim()};try{await refresh();Object.entries({[STORAGE.URL]:session.url,[STORAGE.KEY]:session.key,[STORAGE.STATION]:session.station}).forEach(([k,v])=>localStorage.setItem(k,v));$('#connectionOverlay').classList.add('hidden');}catch(err){$('#connectionMessage').textContent=err.message;$('#connectionMessage').classList.remove('hidden')}});
$('#connectionSettingsButton').onclick=showConnection;$('#refreshButton').onclick=()=>refresh().catch(e=>toast(e.message));$$('.nav-button').forEach(b=>b.onclick=()=>{$$('.nav-button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${b.dataset.view}`));});
$('#participantSearch').oninput=renderParticipants;$('#participantStatusFilter').onchange=renderParticipants;
function openEdit(p,newMode=false){$('#modalTitle').textContent=newMode?'관리자 직접 등록':'신청자 정보 수정';$('#modalContent').innerHTML=`<form id="editForm" class="form-grid"><label>신청자 이름<input name="name" required value="${esc(p?.name||'')}"></label><label>연락처<input name="phone" value="${esc(p?.phone||'')}"></label><label>기관·단체명<input name="organization" value="${esc(p?.organization||'')}"></label><label>참여인원<input name="participantCount" type="number" min="1" max="50" required value="${Number(p?.participantCount||1)}"></label><label>구분<input name="group" value="${esc(p?.group||'')}"></label><label class="wide">좌석 목록<input name="seats" value="${esc((p?.seats||[]).join(', '))}" placeholder="예: A-01, A-02, A-03"></label><p class="wide help-text">좌석을 비우면 미배정 상태가 됩니다. 참여인원 수와 같은 개수의 좌석을 입력하세요. 중복 좌석은 저장되지 않습니다.</p><label class="wide">비고<input name="note" value="${esc(p?.note||'')}"></label><div class="form-actions wide"><button class="button primary">저장</button>${!newMode?'<button id="deleteButton" class="button danger" type="button">신청 삭제</button>':''}</div></form>`;$('#modalBackdrop').classList.remove('hidden');$('#editForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget).entries());v.participantCount=Number(v.participantCount);v.seats=String(v.seats||'').split(',').map(x=>x.trim()).filter(Boolean);try{if(newMode)await jsonp('createParticipant',v);else await jsonp('updateParticipant',{...v,code:p.id});$('#modalBackdrop').classList.add('hidden');await refresh();toast('저장했습니다.')}catch(err){toast(err.message)}};if(!newMode)$('#deleteButton').onclick=async()=>{if(!confirm(`${p.name} 신청을 삭제할까요? 좌석도 즉시 비워집니다.`))return;try{await jsonp('deleteParticipant',{code:p.id});$('#modalBackdrop').classList.add('hidden');await refresh();toast('삭제했습니다.')}catch(err){toast(err.message)}};}
$('#modalCloseButton').onclick=()=>$('#modalBackdrop').classList.add('hidden');$('#newParticipantButton').onclick=()=>openEdit(null,true);document.addEventListener('click',async e=>{const ed=e.target.closest('[data-edit],[data-seat-edit]');if(ed){const id=ed.dataset.edit||ed.dataset.seatEdit,p=state.participants.find(x=>x.id===id);if(p)openEdit(p);return}const c=e.target.closest('[data-checkin]');if(c){try{await jsonp('checkIn',{code:c.dataset.checkin});await refresh();toast('도착 처리했습니다.')}catch(err){toast(err.message)}}const u=e.target.closest('[data-undo]');if(u){try{await jsonp('undoCheckIn',{code:u.dataset.undo});await refresh();toast('도착 처리를 취소했습니다.')}catch(err){toast(err.message)}}});
function parseCode(v){let x=String(v||'').trim();if(x.startsWith('NYJ20|'))x=x.slice(6);try{if(/^https?:/i.test(x))x=new URL(x).searchParams.get('code')||x}catch{}return x}
$('#manualCodeForm').onsubmit=async e=>{e.preventDefault();try{await jsonp('checkIn',{code:parseCode($('#manualCodeInput').value)});$('#manualCodeInput').value='';await refresh();toast('도착 처리했습니다.')}catch(err){toast(err.message)}};
$('#manualSearchForm').onsubmit=e=>{e.preventDefault();const q=$('#manualSearchInput').value.trim().toLowerCase();const list=state.participants.filter(p=>[p.name,p.phone,p.organization,seatText(p)].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,20);$('#manualSearchResults').innerHTML=list.map(p=>`<button class="search-result" data-checkin="${esc(p.id)}"><strong>${esc(p.name)} · ${p.participantCount}명</strong><span>${esc(seatText(p))} / ${p.arrived?'도착완료':'미도착'}</span></button>`).join('')||'<p>일치하는 신청자가 없습니다.</p>';};
$('#eventSettingsForm').onsubmit=async e=>{e.preventDefault();const payload={};['eventName','eventDate','eventVenue','eventOrganizer','seatRows','autoSeatStartRow','publicSubtitle','publicGreeting'].forEach(id=>payload[id]=$('#'+id).value);payload.seatsPerRow=Number($('#seatsPerRow').value);payload.registrationCapacity=Number($('#registrationCapacity').value);payload.registrationOpen=$('#registrationOpen').value==='true';payload.autoAssignSeat=$('#autoAssignSeat').value==='true';try{await jsonp('saveSettings',payload);await refresh();toast('설정을 저장했습니다.')}catch(err){toast(err.message)}};
$('#exportCsvButton').onclick=()=>{const head=['접수번호','신청자','연락처','기관단체','참여인원','좌석','구분','도착여부','등록시각','동의버전','동의시각'];const rows=state.participants.map(p=>[p.number,p.name,p.phone,p.organization,p.participantCount,(p.seats||[]).join(' '),p.group,p.arrived?'도착':'미도착',p.createdAt,p.consentVersion,p.consentAt]);const csv='\ufeff'+[head,...rows].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`20주년_참가자_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);};
if(session.url&&session.key)refresh().then(()=>$('#connectionOverlay').classList.add('hidden')).catch(()=>showConnection());else showConnection();
