'use strict';
const CONFIG = window.NYJ20_CONFIG || {};
const API_URL = String(CONFIG.appsScriptUrl || '').trim();
const PRIVACY = CONFIG.privacy || {};
const $ = s => document.querySelector(s);
let state = { settings: {}, ticket: null };

function showToast(msg, ms=3500){ const t=$('#toast'); t.textContent=msg; t.classList.remove('hidden'); clearTimeout(showToast.timer); showToast.timer=setTimeout(()=>t.classList.add('hidden'),ms); }
function setLoading(on){ $('#loadingOverlay').classList.toggle('hidden',!on); }
function apiReady(){ return /^https:\/\/script\.google\.com\/macros\/s\/.+\/exec/i.test(API_URL); }
function jsonp(action,payload={}){ return new Promise((resolve,reject)=>{ if(!apiReady()) return reject(new Error('Apps Script 주소가 설정되지 않았습니다.')); const cb='__nyj20_'+Date.now()+'_'+Math.random().toString(36).slice(2); const s=document.createElement('script'); const timer=setTimeout(()=>done(new Error('서버 응답 시간이 초과되었습니다.')),Number(CONFIG.requestTimeoutMs)||30000); function done(err,val){clearTimeout(timer);delete window[cb];s.remove();err?reject(err):resolve(val);} window[cb]=r=>{ if(!r||r.ok!==true) return done(new Error(r?.error||'요청 처리에 실패했습니다.')); done(null,r.data);}; const url=new URL(API_URL); url.searchParams.set('action',action); url.searchParams.set('callback',cb); url.searchParams.set('payload',JSON.stringify(payload)); s.onerror=()=>done(new Error('서버에 연결하지 못했습니다.')); s.src=url.toString(); document.head.appendChild(s); }); }
function digits(v){return String(v||'').replace(/\D/g,'');}
function fmtPhone(v){const d=digits(v).slice(0,11); if(d.length>7)return `${d.slice(0,3)}-${d.slice(3,d.length-4)}-${d.slice(-4)}`; if(d.length>3)return `${d.slice(0,3)}-${d.slice(3)}`; return d;}
function seatDisplay(ticket){ const seats=ticket.seats||[]; if(!seats.length)return '좌석 배정 대기'; if(seats.length===1)return seats[0]; const first=seats[0],last=seats[seats.length-1]; const fr=first.split('-')[0], lr=last.split('-')[0]; return fr===lr ? `${first} ~ ${last}` : seats.join(', '); }
function qrPayload(t){return `NYJ20|${t.id}`;}
function ticketLink(code){const u=new URL(location.href);u.search='';u.hash='ticketSection';u.searchParams.set('code',code);return u.toString();}
function renderSettings(settings,counts){state.settings=settings||{}; $('#organizerText').textContent=settings.eventOrganizer||'남양주시장애인복지관'; $('#eventNameText').textContent=settings.eventName||''; $('#subtitleText').textContent=settings.publicSubtitle||''; $('#eventDateText').textContent=settings.eventDate||''; $('#eventVenueText').textContent=settings.eventVenue||''; $('#detailDateText').textContent=settings.eventDate||''; $('#detailVenueText').textContent=settings.eventVenue||''; $('#greetingText').textContent=settings.publicGreeting||''; const full=Number(counts?.remainingCount||0)<=0; const open=settings.registrationOpen!==false&&!full; const status=$('#registrationStatus'); status.className=`registration-status ${open?'open':'closed'}`; status.textContent=open?`현재 신청 가능 · ${Number(counts.registeredPeople||0).toLocaleString()}명 접수 · 잔여 ${Number(counts.remainingCount||0).toLocaleString()}명`:full?'신청 정원이 마감되었습니다.':'현재 온라인 참가 신청이 마감되어 있습니다.'; $('#submitButton').disabled=!open; }
function renderTicket(t,msg=''){ state.ticket=t; $('#ticketNumber').textContent=`NO. ${String(t.number).padStart(4,'0')}`; $('#ticketOrganizer').textContent=state.settings.eventOrganizer||''; $('#ticketEventName').textContent=state.settings.eventName||''; $('#ticketName').textContent=`${t.name} 님`; $('#ticketOrganization').textContent=t.organization||''; $('#ticketSeat').textContent=seatDisplay(t); $('#ticketPeople').textContent=`참여 ${t.participantCount}명`; $('#ticketDate').textContent=state.settings.eventDate||''; $('#ticketVenue').textContent=state.settings.eventVenue||''; $('#ticketMessage').textContent=msg||(t.seats?.length?`${t.participantCount}명 좌석이 함께 배정되었습니다.`:'접수는 완료되었으며 좌석은 운영진이 배정 후 안내합니다.'); const q=$('#ticketQr');q.innerHTML='';new QRCode(q,{text:qrPayload(t),width:192,height:192,correctLevel:QRCode.CorrectLevel.H}); $('#ticketSection').classList.remove('hidden'); history.replaceState(null,'',ticketLink(t.id)); setTimeout(()=>$('#ticketSection').scrollIntoView({behavior:'smooth'}),100); }
async function bootstrap(){ if(!apiReady()){ $('#setupWarning').classList.remove('hidden'); return;} try{const data=await jsonp('publicBootstrap');renderSettings(data.settings,data.counts); const code=new URLSearchParams(location.search).get('code'); if(code){const data2=await jsonp('publicTicket',{code});state.settings=data2.settings;renderTicket(data2.participant,'저장된 접수 정보를 불러왔습니다.');}}catch(e){showToast(e.message,5000);} }

$('#applicationForm').addEventListener('input',e=>{if(e.target.name==='phone')e.target.value=fmtPhone(e.target.value);});
$('#lookupForm').addEventListener('input',e=>{if(e.target.name==='phone')e.target.value=fmtPhone(e.target.value);});
$('#applicationForm').addEventListener('submit',async e=>{e.preventDefault(); const f=new FormData(e.currentTarget); const count=Math.max(1,Math.min(50,Number(f.get('participantCount'))||1)); if(!f.get('consent')) return showToast('개인정보 수집·이용 동의가 필요합니다.'); if(digits(f.get('phone')).length<10)return showToast('연락처를 정확히 입력해 주세요.'); const payload={name:f.get('name'),phone:f.get('phone'),organization:f.get('organization'),participantCount:count,group:f.get('group'),note:f.get('note'),website:f.get('website'),consent:true,consentVersion:PRIVACY.consentVersion||'2026-08-18-v1'}; setLoading(true); try{const data=await jsonp('publicRegister',payload);state.settings=data.settings;renderSettings(data.settings,data.counts);renderTicket(data.participant,data.existing?'이미 접수된 정보가 있어 기존 접수 내용을 불러왔습니다.':'참가 신청이 정상적으로 접수되었습니다.');}catch(err){showToast(err.message,5000);}finally{setLoading(false);} });
$('#lookupForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setLoading(true);try{const d=await jsonp('publicLookup',{name:f.get('name'),phone:f.get('phone')});state.settings=d.settings;renderTicket(d.participant,'접수 정보를 확인했습니다.');}catch(err){showToast(err.message,5000);}finally{setLoading(false);}});
$('#downloadQrButton').addEventListener('click',()=>{if(!state.ticket)return; const c=$('#ticketQr canvas'),img=$('#ticketQr img'); const href=c?c.toDataURL('image/png'):img?.src;if(!href)return showToast('QR 이미지를 준비하지 못했습니다.');const a=document.createElement('a');a.href=href;a.download=`20주년_${state.ticket.number}_${state.ticket.name}_대표QR.png`;a.click();});
$('#copyLinkButton').addEventListener('click',async()=>{if(!state.ticket)return;const link=ticketLink(state.ticket.id);try{await navigator.clipboard.writeText(link);showToast('접수 확인 링크를 복사했습니다.');}catch{window.prompt('아래 링크를 복사해 주세요.',link);}});
function openPrivacy(){ $('#privacyModal').classList.remove('hidden'); document.body.style.overflow='hidden'; }
function closePrivacy(){ $('#privacyModal').classList.add('hidden'); document.body.style.overflow=''; }
$('#privacyOpenButton').addEventListener('click',openPrivacy);$('#privacyCloseButton').addEventListener('click',closePrivacy);$('#privacyModal').addEventListener('click',e=>{if(e.target===$('#privacyModal'))closePrivacy();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closePrivacy();});
$('#privacyRetention').textContent=PRIVACY.retention||'행사 종료 후 사후 정리 완료 시점부터 30일 이내 파기';$('#privacyController').textContent=PRIVACY.controller||'남양주시장애인복지관';$('#privacyContact').textContent=PRIVACY.contact||'기획협력지원팀';
bootstrap();
